version: '3.8'

services:
  roundest-database:
    container_name: roundest-database
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=roundest
      - POSTGRES_PASSWORD=roundest
      - POSTGRES_DB=roundest_db
    ports:
      - 5432:5432
    volumes:
      - roundest-database:/var/lib/postgresql/data
volumes:
  roundest-database: